apiVersion: v1
kind: Service
metadata:
  name: cass-emp-svc
  labels:
    app: cass-emp-svc
spec:
  ports:
  - port: 5000
  #selector chooses the pods
  selector:
    app: cass-emp-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  #Deployment name doesn't matter, pods are attached to service based on "matchLabels"
  name: cass-emp-svc
spec:
  selector:
    matchLabels:
      app: cass-emp-svc
  replicas: 1
  #template describes how pods are created
  template:
    metadata:
      labels:
        app: cass-emp-svc
    spec:
      containers:
      - image: salsanger/peoplesuite_apis:0.0.1-cass
        name: cass-emp-svc
        #download image fresh for every deployment
        imagePullPolicy: Always 
        ports:
        - containerPort: 5000
          name: cass-emp-svc
---
#container and pods created by yaml, but they aren't exposed
#ingress needed to expose service:
  #An API object that manages external access to the services in a cluster, typically HTTP. (kubernetes.io)
  #Ingress may provide load balancing, SSL termination and name-based virtual hosting (kubernetes.io)
#service (prob pod-scope) and ingress (prob cluster-scope) independantly do their own kind of load balancing
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employee-ingr-cass
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /employees
        pathType: Prefix
        backend:
          service:
            name: cass-emp-svc
            port:
              number: 5000