#Note: if service pod is pending, delete mysql pvc then mysql pv's and re-deploy cassandra-service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
  - port: 9042
  selector:
    app: cassandra